services:
    - postgresql

before_script:
    - psql -c 'create database guten_reader_api_test;' -U postgres
    - cp config/database.yml.travis config/database.yml

language: ruby

rvm:
    - 2.6.3

script:
    - bundle exec rails db:create db:migrate RAILS_ENV=test
    - bundle exec rails db:create db:migrate db:seed RAILS_ENV=production
    - bundle exec rails db:create db:migrate db:seed RAILS_ENV=development
    - bundle exec rspec
