services:
    - postgresql

before_script:
    - psql -c 'create database guten-reader-api_test;' -U postgres
    - cp config/database.yml.travis config/database.yml

language: ruby

rvm:
    - 2.6.3

script:
    - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
    - bundle exec rspec